---
- name: Setting up environment and running monitoring stack
  hosts: metrics-lab
  become: true

  roles:
    - role: ableton.prometheus_node_exporter

  tasks:
    - name: Upgrade all system packages
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Synchronize system date and time
      block:
        - name: Ensure systemd-timesyncd is installed
          ansible.builtin.apt:
            name: systemd-timesyncd
            state: present
        - name: Ensure systemd-timesyncd is enabled and running
          ansible.builtin.systemd:
            name: systemd-timesyncd
            enabled: true
            state: started

    - name: Installing Docker and Docker Compose
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose-v2
        state: present
        update_cache: yes

    - name: Launch monitoring stack using Docker Compose
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: /vagrant/docker/
      register: docker_compose_output
